### ISSUE TITLE
Suggestion: rename create_date field to created

### ISSUE THREAD

**Issue by rg3915** [Abdenasser/dr_scaffold#51]
I suggest rename `create_date` to `created`.

Because if you want to use (CursorPagination)(https://www.django-rest-framework.org/api-guide/pagination/#cursorpagination) you need of the `created` field. And particularly I find this a more conventional name.

**Comment by matej2** [comment]
This project is dead

**Comment by rg3915** [comment]
of course not

**Comment by matej2** [comment]
Oh hello there. 
I thought that because my issues were not addressed at all. And also because latest updates were only readme file.

Anyway, I had some ideas for this project, you probably havent see them.

**Comment by matej2** [comment]
Anyway, I am thinking about making a separate version of this project. The one that would not require Django as a dependency.

**Comment by rg3915** [comment]
@matej2 make fork.

**Comment by Abdenasser** [comment]
@matej2 even if the repo is not very active in the latest period it doesn't mean we are giving up on it, this is a community project maintained by community members who are also human beings that are involved in other stuff and have a real-life, you can feel free to fork the project and do whatever you want with it as well as that you can also feel free to contribute and submit some PRs instead of just waiting for maintainers to address your issues (even though we haven't seen any big issues that worth considering and working on yet).

dr_scaffold is not a framework or library it's just a python package that leverages Django management commands with some extra power to generate files for DRF so don't expect it to be very active as other open-source libs of frameworks you see in GitHub, you can look at it as any django command ex. `startapp` it does what you need but its core hasn't changed since so long... it does pretty much what it is created for already.

Finally, I think that you've been already served, now it's your turn to contribute if you really mean to help other people as well not just yourself!

**Comment by matej2** [comment]
When you generally develop code generators you want them to be independent on technology. I dont see the reason why df_scafford would use Django, Python also provides functionality that helps you develop cli tools.

Already been served? I found a bug but you just scrapped it off. I dont understand why some attributes are optional and some not. How is this not an issue?

**Comment by rg3915** [comment]
Will you make a new release with the new changes?
